### ISSUE TITLE
lib/sunzi/cloud/digital_ocean.rb:58:in `choose': undefined method `first' for nil:NilClass

### ISSUE THREAD

**Issue by ethnt** [kenn/sunzi#35]
I'm having issues setting up DigitalOcean instances with Sunzi. Here's my `digital_ocean.yml` file:

``` yaml

---
api_key: [REDACTED]
client_id: [REDACTED]

# add / remove environments
environments:
  - production
  - staging
fqdn:
  zone: getikat.com
  production: '%{host}.getikat.com'
  staging: '%{host}.staging.getikat.com'
name:
  production: 'ikat-%{host}'
  staging: 'ikat-staging-%{host}'

# filter out large lists by keyword
distributions_filter: ubuntu
```

Here's the error I'm getting:

```
$ bundle exec sunzi setup digital_ocean
environment? (production / staging): staging
hostname? (only the first part of subdomain): lmd
/Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/sunzi-cd4b3800e60e/lib/sunzi/cloud/digital_ocean.rb:58:in `choose': undefined method `first' for nil:NilClass (NoMethodError)
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/sunzi-cd4b3800e60e/lib/sunzi/cloud/digital_ocean.rb:7:in `do_setup'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/sunzi-cd4b3800e60e/lib/sunzi/cloud/base.rb:38:in `setup'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/sunzi-cd4b3800e60e/lib/sunzi/cloud.rb:17:in `method_missing'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/sunzi-cd4b3800e60e/lib/sunzi/cli.rb:27:in `setup'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/sunzi-cd4b3800e60e/bin/sunzi:8:in `<top (required)>'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bin/sunzi:23:in `load'
    from /Users/ethan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bin/sunzi:23:in `<main>'
```

I'm not sure what's happening here — this is happening with the current release and the current commit on master.
